pointcloud_to_laserscan:
  ros__parameters:
    target_frame: "odom"
    transform_tolerance: 0.01
    min_height: 0.1
    max_height: 3.0
    angle_min: -3.14  # -90 degrees
    angle_max: 3.14   # 90 degrees
    angle_increment: 0.01
    scan_time: 0.1
    range_min: 0.8
    range_max: 200.0
    use_inf: true
    inf_epsilon: 1.0
